---
- name: Install Docker server and Docker-compose
  gather_facts: no
  hosts: docker
  become: true
  tasks:
    - name: Install Docker prerequisites
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg 
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker CE
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Add vagrant user in docker group
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Download Docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.3/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 0755

    - name: Create project directory
      file:
        path: ~/nginx/www
        state: directory
        mode: 0755

    - name: Copy files for docker-compose
      copy:
        src: nginx/
        dest: ~/nginx/

    - name: Copy files for the webpage
      copy:
        src: www/
        dest: ~/nginx/www/

      
