---
- name: Install Docker server
  gather_facts: no
  hosts: docker
  become: true
  tasks:
    - name: Install Docker prerequisites
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg 
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker CE
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: Add vagrant user in docker group
      user:
        name: vagrant
        groups: docker
        append: yes
