# ####################################################################
# ################### CONFIGURATION VARIABLES ########################
# ####################################################################
IMAGE_NAME = "ubuntu/bionic64"      # Image to use
MEM = 4096                          # Amount of RAM
CPU = 2                             # Number of processors

DOCKER_IP = "10.0.43.10"

Vagrant.configure("2") do |config|
  # RAM and CPU config
  config.vm.provider "virtualbox" do |v|
    v.memory = MEM
    v.cpus = CPU
  end

  # docker config
  config.vm.define "docker" do |docker|
    docker.vm.box = IMAGE_NAME
    docker.vm.hostname = "docker"
    docker.vm.network "private_network", ip: "#{DOCKER_IP}"
    docker.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    end
  end
end
